PROC=callgraph
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)callgraph$(O): $(I)area.hpp $(I)bytes.hpp $(I)fpro.h $(I)funcs.hpp       \
	          $(I)gdl.hpp $(I)graph.hpp $(I)ida.hpp $(I)idp.hpp         \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)netnode.hpp $(I)pro.h     \
	          $(I)segment.hpp $(I)ua.hpp $(I)xref.hpp callgraph.cpp     \
	          callgraph.h
