PROC=tracer
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)tracer$(O)  : $(I)area.hpp $(I)bytes.hpp $(I)dbg.hpp $(I)fpro.h         \
	          $(I)funcs.hpp $(I)ida.hpp $(I)idd.hpp $(I)idp.hpp         \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)netnode.hpp $(I)pro.h     \
	          $(I)segment.hpp $(I)ua.hpp $(I)xref.hpp tracer.cpp
