PROC=uiswitch
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)uiswitch$(O): $(I)area.hpp $(I)auto.hpp $(I)bytes.hpp $(I)demangle.hpp  \
	          $(I)fixup.hpp $(I)fpro.h $(I)frame.hpp $(I)funcs.hpp      \
	          $(I)ida.hpp $(I)idd.hpp $(I)idp.hpp $(I)ieee.h            \
	          $(I)ints.hpp $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp  \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)offset.hpp $(I)pro.h $(I)queue.hpp $(I)segment.hpp    \
	          $(I)srarea.hpp $(I)struct.hpp $(I)typeinf.hpp $(I)ua.hpp  \
	          $(I)xref.hpp $(I)intel.hpp uiswitch.cpp
