PROC=funclist
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)funclist$(O): $(I)area.hpp $(I)auto.hpp $(I)bytes.hpp $(I)demangle.hpp  \
	          $(I)entry.hpp $(I)fpro.h $(I)funcs.hpp $(I)ida.hpp        \
	          $(I)idp.hpp $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp   \
	          $(I)loader.hpp $(I)nalt.hpp $(I)name.hpp $(I)netnode.hpp  \
	          $(I)pro.h $(I)segment.hpp $(I)typeinf.hpp $(I)ua.hpp      \
	          $(I)xref.hpp funclist.cpp
