PROC=ugraph2
!include ..\plugin.mak

# MAKEDEP dependency list ------------------
$(F)ugraph2$(O) : $(I)area.hpp $(I)bytes.hpp $(I)fpro.h $(I)funcs.hpp       \
	          $(I)gdl.hpp $(I)graph.hpp $(I)ida.hpp $(I)idp.hpp         \
	          $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp               \
	          $(I)loader.hpp $(I)nalt.hpp $(I)netnode.hpp $(I)pro.h     \
	          $(I)segment.hpp $(I)ua.hpp $(I)xref.hpp ugraph2.cpp
